name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: tesHeroExtend
      id: tesheroextend
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: tesHeroExtend
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testExtendHero"
        timeout: 10
        max-score: 3
    - name: testHeroConstructor
      id: testheroconstructor
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testHeroConstructor
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testConstructor"
        timeout: 10
        max-score: 2
    - name: testHeroAttack
      id: testheroattack
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testHeroAttack
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testAttack"
        timeout: 10
        max-score: 2
    - name: testClericExtend
      id: testclericextend
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testClericExtend
        setup-command: ''
        command: ' sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo
          update-locale && gradle test --tests "ClericTest.testExtendHero"'
        timeout: 10
        max-score: 3
    - name: testClericConstructor
      id: testclericconstructor
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testClericConstructor
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ClericTest.testConstructor"
        timeout: 10
        max-score: 2
    - name: testClericAttack
      id: testclericattack
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testClericAttack
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ClericTest.testAttack"
        timeout: 10
        max-score: 2
    - name: testMain
      id: testmain
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testMain
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgA1Test.testMain"
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESHEROEXTEND_RESULTS: "${{steps.tesheroextend.outputs.result}}"
        TESTHEROCONSTRUCTOR_RESULTS: "${{steps.testheroconstructor.outputs.result}}"
        TESTHEROATTACK_RESULTS: "${{steps.testheroattack.outputs.result}}"
        TESTCLERICEXTEND_RESULTS: "${{steps.testclericextend.outputs.result}}"
        TESTCLERICCONSTRUCTOR_RESULTS: "${{steps.testclericconstructor.outputs.result}}"
        TESTCLERICATTACK_RESULTS: "${{steps.testclericattack.outputs.result}}"
        TESTMAIN_RESULTS: "${{steps.testmain.outputs.result}}"
      with:
        runners: tesheroextend,testheroconstructor,testheroattack,testclericextend,testclericconstructor,testclericattack,testmain
